### ISSUE TITLE
Feature request: error messages in UI

### ISSUE THREAD

**Issue by chiarng** [Meshiest/glitch#1]
As an end user, it's unclear why adding items to the map sometimes doesn't work. 

429
`{"message":"Too many requests"}`

I suggest adding UI error message banners to clarify for the end user what is happening. 
e.g. "Please try adding data point again in X seconds, user has sent too many requests recently."

**Comment by Meshiest** [comment]
will get right to that!

**Comment by Meshiest** [comment]
https://github.com/Meshiest/glitch/commit/c655284d2818a3f2410f67ebe77781f9417fe223

with this commit users will see a 10 second cooldown instead of an "add" hyperlink!
